CREATE TABLE IF NOT EXISTS college2 (
    FID INT(11) AUTO_INCREMENT,
    IPEDSID VARCHAR(45) DEFAULT NULL,
    NAME VARCHAR(150) DEFAULT NULL,
    ADDRESS VARCHAR(100) DEFAULT NULL,
    ZIP VARCHAR(50) DEFAULT NULL,
    TELEPHONE VARCHAR(50) DEFAULT NULL,
    LATITUDE VARCHAR(45) DEFAULT NULL,
    LONGITUDE VARCHAR(45) DEFAULT NULL,
    TOT_ENROLL VARCHAR(50) DEFAULT NULL,
    HOUSING VARCHAR(50) DEFAULT NULL,
    DORM_CAP VARCHAR(50) DEFAULT NULL,
    TOT_EMPLOY VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (FID)
);