CREATE TABLE IF NOT EXISTS college1 (
    ID INT(11) AUTO_INCREMENT,
    UNITID VARCHAR(50) DEFAULT NULL,
    OPEID VARCHAR(50) DEFAULT NULL,
    OPEID6 VARCHAR(50) DEFAULT NULL,
    INSTNM VARCHAR(150) DEFAULT NULL,
    CITY VARCHAR(50) DEFAULT NULL,
    STABBR VARCHAR(50) DEFAULT NULL,
    INSTURL VARCHAR(200) DEFAULT NULL,
    NPCURL VARCHAR(200) DEFAULT NULL,
    UGDS VARCHAR(45) DEFAULT NULL,
    GRAD_DEBT_MDN_SUPP VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (ID)
);



