CREATE TABLE IF NOT EXISTS college2 (
    FID INT(11) AUTO_INCREMENT,
    IPEDSID VARCHAR(45) DEFAULT NULL,
    NAME VARCHAR(100) DEFAULT NULL,
    ADDRESS VARCHAR(100) DEFAULT NULL,
    ZIP VARCHAR(10) DEFAULT NULL,
    TELEPHONE VARCHAR(20) DEFAULT NULL,
    LATITUDE VARCHAR(45) DEFAULT NULL,
    LONGITUDE VARCHAR(45) DEFAULT NULL,
    TOT_ENROLL VARCHAR(10) DEFAULT NULL,
    HOUSING VARCHAR(10) DEFAULT NULL,
    DORM_CAP VARCHAR(10) DEFAULT NULL,
    PRIMARY KEY (FID)
);
